name: $(Date:yyyyMMdd)$(Rev:.rrr)-$(BuildID)

variables:
  name: "codingquiz"
  appPath: "frontend"
  artifactName: "frontend"
  buildAgentImage: "ubuntu-18.04"
  buildAgentChromeVersion: 81

resources:
  repositories:
    - repository: "self"
      trigger:
        paths:
          include:
          - "frontend/"

stages:
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: "frontend"
        displayName: "Frontend"
        pool:
          vmImage: "$(buildAgentImage)"
          demands: "npm"
        steps:
        - task: NodeTool@0
          displayName: "use node 10"
          inputs:
            versionSpec: 10

        - task: Npm@1
          displayName: "npm install"
          inputs:
            workingDir: "$(appPath)"
            verbose: false

        - task: Npm@1
          displayName: "npm lint"
          inputs:
            workingDir: "$(appPath)"
            command: "custom"
            customCommand: "run lint"

        - task: Npm@1
          displayName: "npm test:unit:ci"
          inputs:
            workingDir: "$(appPath)"
            command: "custom"
            customCommand: "run test:unit:ci"

        - task: PublishTestResults@2
          displayName: "publish unit tests"
          inputs:
            testResultsFiles: "$(appPath)/junit.xml"
            testRunTitle: "unit tests"
            failTaskOnFailedTests: true
            mergeTestResults: true

        - task: PublishCodeCoverageResults@1
          displayName: "publish code coverage"
          inputs:
            codeCoverageTool: "Cobertura"
            summaryFileLocation: "$(appPath)/coverage/cobertura-coverage.xml"
            failIfCoverageEmpty: true

        - script: |
            google-chrome --version
            cd $(appPath)
            npm i --save-dev chromedriver@$(buildAgentChromeVersion)
          displayName: "set chromedriver version"

        - task: Npm@1
          displayName: "npm test:e2e:ci"
          inputs:
            workingDir: "$(appPath)"
            command: "custom"
            customCommand: "run test:e2e:ci"

        - task: PublishTestResults@2
          displayName: "publish e2e tests"
          inputs:
            testResultsFiles: "$(appPath)/tests/e2e/reports/*.xml"
            testRunTitle: "e2e tests"
            failTaskOnFailedTests: true
            mergeTestResults: true

        - task: Npm@1
          displayName: "npm build"
          inputs:
            workingDir: "$(appPath)"
            command: "custom"
            customCommand: "run build"

        - publish: "$(appPath)/dist" 
          displayName: "publish artifact"
          artifact: "$(artifactName)"

  - stage: "deploy_development"
    displayName: "Deploy development"
    dependsOn: "build"
    jobs:
      - deployment: "development"
        environment: "development"
        pool:
          vmImage: "windows-latest" # AzureFileCopy@3 doesn't work with ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "frontend/environment-deploy.yml"
                  parameters:
                    artifactName: $(artifactName)
                    storageAccountName: "st$(name)d"

  - stage: "deploy_test"
    displayName: "Deploy test"
    dependsOn: "deploy_development"
    jobs:
    - deployment: "test"
      environment: "test"
      pool:
        vmImage: "windows-latest"
      strategy:
        runOnce:
          deploy:
            steps:
              - template: "frontend/environment-deploy.yml"
                parameters:
                  artifactName: $(artifactName)
                  storageAccountName: "st$(name)t"